# Few-shot examples for progressive trials
# These are shown to models before tasks to teach Faber syntax

examples:
  - id: example_variable
    typescript: |
      const x = 5
    faber: |
      fixum x = 5
    explanation: "Constants use 'fixum', variables use 'varia'"

  - id: example_function
    typescript: |
      function double(x: number): number {
        return x * 2
      }
    faber: |
      functio double(numerus x) -> numerus {
        redde x * 2
      }
    explanation: "Functions use 'functio' with type-first params (numerus x), return uses 'redde'"

  - id: example_conditional
    typescript: |
      if (x > 10) {
        console.log("big")
      } else {
        console.log("small")
      }
    faber: |
      si x > 10 {
        scribe "big"
      } secus {
        scribe "small"
      }
    explanation: "If/else uses 'si/secus', console.log uses 'scribe'"

  - id: example_loop
    typescript: |
      for (const item of items) {
        console.log(item)
      }
    faber: |
      ex items pro item {
        scribe item
      }
    explanation: "For-of loops use 'ex...pro'"

  - id: example_array
    typescript: |
      const nums = [1, 2, 3]
    faber: |
      fixum nums = [1, 2, 3]
    explanation: "Arrays use same syntax as TypeScript"

  - id: example_boolean
    typescript: |
      const flag = true
    faber: |
      fixum flag = verum
    explanation: "Boolean literals: verum (true), falsum (false)"

  - id: example_null
    typescript: |
      const value = null
    faber: |
      fixum value = nihil
    explanation: "Null is 'nihil'"

  - id: example_type_annotation
    typescript: |
      const name: string = "Alice"
    faber: |
      fixum textus name = "Alice"
    explanation: "Type annotations use type-first syntax: fixum textus name (not name: textus)"

  - id: example_while_loop
    typescript: |
      while (x > 0) {
        x = x - 1
      }
    faber: |
      dum x > 0 {
        x = x - 1
      }
    explanation: "While loops use 'dum'"

  - id: example_object_literal
    typescript: |
      const person = { name: "Bob", age: 30 }
    faber: |
      fixum person = { name: "Bob", age: 30 }
    explanation: "Object literals use same syntax as TypeScript"
